name: Run R Visualizations

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install Packages
        run: |
          Rscript -e "install.packages(c('tidyverse','ggplot2','reshape2','cowplot','corrplot'))"

      - name: Run Visualization Script
        run: |
          Rscript scripts/04_visualization.R

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: visualization_results
          path: output/
